# Generated by Django 5.1.7 on 2025-04-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='visitor_count',
            field=models.IntegerField(default=0),
        ),
    ]
